-- Flyway migration: create job_data table matching JPA entity
CREATE TABLE IF NOT EXISTS job_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" VARCHAR(255),
  employer VARCHAR(255),
  location VARCHAR(255),
  job_title VARCHAR(255),
  years_at_employer NUMERIC(10,2),
  years_of_experience NUMERIC(10,2),
  salary NUMERIC(20,2),
  signing_bonus NUMERIC(15,2),
  annual_bonus NUMERIC(15,2),
  annual_stock_value_bonus VARCHAR(255),
  gender VARCHAR(255),
  additional_comments TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_title ON job_data (job_title);
CREATE INDEX IF NOT EXISTS idx_salary ON job_data (salary);
CREATE INDEX IF NOT EXISTS idx_gender ON job_data (gender);
